#!/bin/bash

set -o errexit
set -o pipefail
# if any variables are not set exit 
set -o nounset

python3 manage.py migrate --no-input
python3 manage.py collectstatic --no-input
python3 manage.py runserver 0.0.0.0:8000
